
### Old Recommendations

The Readiness Score is one of several features of the Ivy that can be marketed as a value-add over the FitBit devices in the data set. The feature makes use of several functions of the device, some of which the FitBits in the data set do not have, and builds on other features already available, like Respiratory Rate and Resting Heart Rate.

* Most users are not logging sleep
* Those that are appear to already be getting high-quality sleep
* There is nothing to indicate the use of the FitBits improved the quantity or quality of their sleep above this high baseline

* Don't market this feature as something that will improve your sleep
* Instead, given the consistency of users in getting their sleep, as evidenced by the small correlation with time for sleep quantity and quality, the Sleep Tracking could be marketed more as a way of tracking and reinforcing the user's existing good sleep habits 
* As with the Readiness Score, marketing teams could frame the feature more as a way of getting a heads-up on days where you haven't slept well, since most of the time the feature would just tell users (from this cohort, at least) that they just had a reasonably good night's sleep. This would work well with the "track existing habits" marketing angle: think "You're great at giving your body the sleep it needs, but for those nights where things just don't work out, Ivy can give you guidance on whether you're up for the day, or better off taking it down a notch to recover."
* If it exists, highlight a manual-activation mode for the Sleep Tracking mode. The low amount of non-Asleep data in this data set may be a result of people mostly using the automatic mode, which is convenient, but doesn't track time spent *trying* to get to sleep: a manual-activation feature could therefore be pushed harder as a sort of second feature that gets better data on how you go getting to sleep.

> Consumer behaviour may be conducive to the Resting Heart Rate feature

* Existing consumers do not make much use of heart rate tracking overnight, despite this being a key part of the functionality of the Resting Heart Rate feature. Consumers do, however, log a lot of day-time data, and the majority of this data indicates low-intensity conditions. Current user behaviors are therefore conducive to the Resting Heart Rate feature, but may result in higher-than-expected values as the RHR data will be skewed towards time spent awake rather than time spent asleep

* In order to match current user behaviours, the marketing for the Resting Heart Rate should emphasise daytime usage: for instance, advertise that the feature will help understand your resting heart rate during your work day, 
* The data indicates that users typically do not log overnight, which may impact the performance of this feature: part of the usefulness of the feature comes from calibrating the data based on overnight heart-rate, so if users are not wearing overnight, the resting heart rate value may be skewed upward s as it is based primarily on daytime usage
* The marketing should therefore encourage users to wear overnight, highlighting the synergy between this and the Readiness Score feature to maximise the likelihood that users wear overnight, and therefore the accuracy of both features
* If users do not wear their devices overnight, they are unlikely to see the benefits and may consider other, less-featured but cheaper devices for their next purchase

Features without Data

* These features can all be marketed as improvements and additions over the functionality of existing FitBits.
* As discussed with regards to the Readiness score, marketing for any feature that requires overnight wear, like the Cardiac Coherence tracking, should take into account the low utilisation of existing overnight functions like sleep tracking seen in the existing data.
